import { Language } from '../types';

export const translations = {
  en: {
    title: "UI2GA",
    subtitle: "AI Tagging Architect",
    reset: "Reset",
    analyze: "UI Analysis Start",
    analyzing: "Analyzing...",
    reAnalyze: "UI Analysis Start",
    uploadTitle: "Transform UI Screenshots into GA Plans",
    uploadDesc: "Upload screenshots, define rules, and let AI generate exhaustive tagging.",
    clickDrag: "Screenshot click or drop",
    supports: "JPG, PNG support (Multiple allowed)",
    regionSelected: "Region Selected",
    analyzeFull: "Analyze full image or drag to select area",
    analysisFailed: "Analysis Failed",
    tryAgain: "Try Again",
    ready: "Ready for Analysis",
    readyDesc: "Select an area (optional) or enter rules, then click the Analysis button.",
    summary: "Summary",
    table: "Table",
    json: "JSON",
    copyMarkdown: "Copy Markdown",
    copyJSON: "Copy JSON",
    contextRules: "Rules & Context",
    customRulesTitle: "Custom Rules",
    existingTagsTitle: "Existing Screen GA",
    customRulesPlaceholder: "E.g., 'Use prefix tap_ for all buttons', 'Ignore footer links'...",
    existingTagsPlaceholder: "If you paste existing GA tags used in current screens, they will be expanded with same rules.",
    screenshots: "Screenshots",
    addMore: "Add",
    noSummary: "No summary available.",
    editMode: "Double click cell to edit",
    addRow: "Add Row",
    deleteRow: "Delete",
    downloadAnnotated: "Annotated Image Download",
    exportFigma: "Figma export",
    noOverlays: "No overlays to export",
    annotationMode: "Annotation : Drag to add new tag",
    dragToSelect: "Drag to select analysis area",
    regionSelectedMsg: "Region Selected",
    shortcutHint: "Spacebar + Drag: Pan | Scroll: Zoom",
    // New keys for multi-selection and analysis feedback
    noSelection: "No screenshots selected.",
    analyzeSummary: "Will analyze {total} screenshots ({partial} selected areas, {full} full screens)",
    analyzingBtn: "Stop Analysis",
    analyzeBtn: "Analyze UI",
    canceledStatus: "Canceled. {completed}/{total} completed.",
    features: {
      detection: { title: "Precise UI Detection", desc: "Automatic detection of key interactions like buttons, inputs, toggles, lists" },
      selection: { title: "Interactive Analysis", desc: "Select and focus tagging only on areas you want to analyze" },
      multi: { title: "Multi-Screen Analysis", desc: "Design user flows by connecting multiple screens" }
    }
  },
  ko: {
    title: "UI2GA",
    subtitle: "AI 태깅 아키텍트",
    reset: "초기화",
    analyze: "UI 분석 시작",
    analyzing: "분석 중...",
    reAnalyze: "UI 분석 시작",
    uploadTitle: "UI 스크린샷을 GA 태깅 기획안으로",
    uploadDesc: "스크린샷을 업로드하면 AI가 화면 구조를 이해해 태깅 명세서를 만들어드립니다.",
    clickDrag: "스크린샷 클릭 또는 드롭",
    supports: "JPG, PNG 지원 (다중 업로드 가능)",
    regionSelected: "영역 선택됨",
    analyzeFull: "전체 이미지 분석 또는 드래그하여 영역 선택",
    analysisFailed: "분석 실패",
    tryAgain: "다시 시도",
    ready: "분석 준비 완료",
    readyDesc: "영역을 선택하거나(선택 사항) 규칙을 입력한 후 분석 버튼을 누르세요.",
    summary: "요약",
    table: "태깅 테이블",
    json: "JSON 출력",
    copyMarkdown: "마크다운 복사",
    copyJSON: "JSON 복사",
    contextRules: "규칙 및 컨텍스트",
    customRulesTitle: "커스텀 규칙",
    existingTagsTitle: "기존 화면 GA",
    customRulesPlaceholder: "예: '모든 버튼에 tap_ 접두사 사용', '드롭다운 메뉴 무시'...",
    existingTagsPlaceholder: "기존 화면에서 사용 중인 GA 태그를 붙여넣으면, 동일한 규칙으로 확장됩니다.",
    screenshots: "스크린샷",
    addMore: "추가",
    noSummary: "요약 정보가 없습니다.",
    editMode: "셀을 더블 클릭하여 수정",
    addRow: "행 추가",
    deleteRow: "삭제",
    downloadAnnotated: "주석 이미지 다운로드",
    exportFigma: "Figma로 내보내기",
    noOverlays: "내보낼 주석이 없습니다",
    annotationMode: "주석 모드: 드래그하여 새 태그 추가",
    dragToSelect: "드래그하여 분석 영역 선택",
    regionSelectedMsg: "영역 선택됨",
    shortcutHint: "Spacebar + 드래그: 이동 | 스크롤: 확대/축소",
    // New keys for multi-selection and analysis feedback
    noSelection: "선택된 스크린샷이 없습니다.",
    analyzeSummary: "분석 대상 {total}개 (선택영역 {partial}, 전체화면 {full})",
    analyzingBtn: "UI 분석 중지",
    analyzeBtn: "UI 분석 시작",
    canceledStatus: "중지됨. {completed}/{total} 완료.",
    features: {
      detection: { title: "정밀 UI 인식", desc: "버튼, 입력창, 토글, 리스트 등 주요 인터랙션 자동 탐지" },
      selection: { title: "인터랙티브 분석", desc: "분석하고 싶은 영역만 직접 선택해 집중 태깅" },
      multi: { title: "멀티 스크린 분석", desc: "여러 화면을 연결해 사용자 흐름까지 함께 설계" }
    }
  }
};

export const getTexts = (lang: Language) => translations[lang];